<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OPP MVC PHP</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/aos/dist/aos.js"></script>
</head>


<body class="d-flex flex-column h-100">
    <nav class="navbar navbar-expand-lg bg-body-secondary fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="http://localhost/oop_mvc/?page=home">OOP_MVC</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <?php foreach (CONFIG_ROUTES as $key => $value) : ?>
                        <li class="nav-item">
                            <a class="nav-link <?php if ($page === $key) echo "active"; ?>" href="?page=<?= $key ?>">
                                <?= $value ?>
                            </a>


                        </li>

                        
                    <?php endforeach ?>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </a>
                        <ul class="dropdown-menu">
                        <?php if (!isset($_SESSION['user'])): ?>
                            <li><a class="dropdown-item" href="?page=login">Login</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="?page=register">Register</a></li>
                            <?php else: ?>
                            <li><a class="dropdown-item" href="?page=adminlist">Adminlist</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="?page=logout">Logout</a></li>
                            <?php endif ?>
                        </ul>
                    </li>
                </ul>





                    <button class="btn btn-primary" id="toggleButton">Toggle Background</button>


                </ul>
                <form class="d-flex" role="search">
                    <input name="page" value="search" type="hidden">
                    <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
<body>




<h1>It Works!!</h1>

<?php echo $content;?>

<footer class="bg-body-secondary footer mt-auto p-3">
        <section class="container-fluid text-center">
           
            
                <div class="bottom-right">
                <button id="scrollTopButton" onclick="scrollToTop()">^</button>
            </div>
            &copy; DWWM OOP_MVC_VERSION

           





            <script>







  

   // Fonction pour faire défiler la page vers le haut
function scrollToTop() {
  window.scrollTo({
    top: 0,
    behavior: 'smooth' // Pour une animation fluide, si pris en charge par le navigateur
  });
}



AOS.init();


</script>


           
        </section>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    
</body>
</html>
