



    <?php
/**
 * Il peut s'avérer pratique de récupérer ici $data
 * Et éventuellement de déclarer des variables de traitement
 * */
$pictures = $data['pictures'];
?>
<h1 class="text-center">Gallery</h1>

<section  class="row">
<?php foreach ($pictures as $pic) : ?>

<article class="col-12 col-sm-6 col-md-4">
  <div  class="card mb-3" data-aos="fade-up">
  <a href="<?= "?page=detail&id=".$pic['id'] ?>">
    <img src="<?= $pic['src'] ?>" class="card-img-top" class="img-fluid" width="550px" height="550px" alt="<?= $pic['title'] ?>">
  </a>
    <div class="card-body" data-aos="fade-down">
    <a class="text-dark text-decoration-none" href="<?= "?page=detail&id=".$pic['id'] ?>">
      <h4 class="card-title"><?= $pic['title'] ?></h4>
    </a>
      <p class="card-text"><?= $pic['description'] ?></p>
      <p class="card-text"><?= $pic['author'] ?></p>
      <a href="<?= "?page=detail&id=".$pic['id'] ?>" class="btn btn-secondary">En savoir davantage</a>
    </div>
  </div>
</article>

<?php endforeach ?>
</section>

     